version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: x86
clone_folder: c:\project\source
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake c:\project\source -G "Visual Studio 15"
build:
  verbosity: minimal