version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\project\source
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake c:\project\source -G "Visual Studio 15"

    cmake --build . --config "Release"
test_script:
  - c:\project\source\build\tests\Release\MathExpressionTest.exe