dot_operator ::= "*" | "**" | "/" | "//" | "%"
custom_operator ::= 
weak_operator ::= "+" | "-" | custom_operator
self_operator ::= "~" | "!" | custom_operator

math_expression ::= math_term (weak_operator math_term)*
math_value ::= math_expression | direct_value
math_term ::= self_operator? (math_value | "(" condition_chain_expression ")") (dot_operator math_value)*

condition_operator ::= "<" | ">" | "<=" | ">=" | "==" | "!="
condition_expression ::= math_expression (condition_opeartor math_expression)*

bit_operator ::= "&" | "|" | "^"
bit_expression ::= condition_expression (bit_operator condition_expression)*

condition_chain_operator ::= "&&" | "||"
condition_chain_expression ::= bit_expression (condition_chain_operator bit_expression)*

expression ::= condition_chain_expression