string ::= raw_string | normal_string | template_string

delimiter ::= L*
raw_string ::= 'R"' delimiter "(" raw_content* ")" delimiter '"'

escape_character ::= "\" ("n" | "r" | "t")
normal_content ::= escape_character | [^"']
normal_string ::= '"' ('\"' | "'" | normal_content)* '"' | "'" ("\'" | '"' | normal_content)* "'"

template_content ::= "${" statement "}"
template_string ::= "`" (normal_content | ["'] | template_content)* "`"