constant ::= "null" | "true" | "false" | number
member ::= identifier ("." identifier)* parameter_list?
value ::= constant | member

parameter_list = "(" (expression ("," expression)*)? ")"

arithmetic_operator ::= "*" | "/" | "%" | "+" | "-" | "//" | "**"
bit_operator ::= "&" | "|" | "^"
self_operator ::= "not" | "~"
condition_chain_operator ::= "and" | "or"
compare_operator ::= "<" | ">" | "<=" | ">=" | "==" | "!=" | "<=>" | "is" | "is not"

term ::= self_operator? value
expression ::= term ((arithmetic_operator | bit_operator | condition_chain_operator | compare_operator) term)*