name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake .. -DBIA_BUILD_EXAMPLES=OFF
    - name: make
      run: cd build && cmake --build . -- -j
    - name: test
      run: cd build && ctest
