name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

defaults:
  run:
    working-directory: ./build

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ls -la && pwd && cmake .. -DBIA_BUILD_EXAMPLES=OFF
    - name: make
      run: cmake --build . -- -j
    - name: test
      run: ctest
